events {}

http {
    upstream auth_service {
        server auth-service:8000;
    }

    upstream product_service {
        server product-service:8000;
    }

    upstream inventory_service {
        server inventory-service:8000;
    }

    upstream cart_service {
        server cart-service:8000;
    }

    upstream order_service {
        server order-service:8000;
    }

    upstream payment_service {
        server payment-service:8000;
    }

    server {
        listen 80;

        location /api/v1/auth/ {
            proxy_pass http://auth_service;
        }

        location /api/v1/products/ {
            proxy_pass http://product_service;
        }

        location /api/v1/inventory/ {
            proxy_pass http://inventory_service;
        }

        location /api/v1/cart/ {
            proxy_pass http://cart_service;
        }

        location /api/v1/orders/ {
            proxy_pass http://order_service;
        }

        location /api/v1/payments/ {
            proxy_pass http://payment_service;
        }
    }
}