events {}

http {

    upstream auth-service {
        server host.docker.internal:8001;
    }

    upstream product-service {
        server host.docker.internal:8002;
    }

    upstream inventory-service {
        server host.docker.internal:8003;
    }

    upstream cart-service {
        server host.docker.internal:8004;
    }

    upstream order-service {
        server host.docker.internal:8005;
    }

    upstream payment-service {
        server host.docker.internal:8006;
    }

    server {
        listen 80;

        # Auth Service
        location /api/v1/auth/ {
            proxy_pass http://auth-service;
        }

        # Product Service
        location /api/v1/products/ {
            proxy_pass http://product-service;
        }

        # Inventory Service
        location /api/v1/inventory/ {
            proxy_pass http://inventory-service;
        }

        # Cart Service
        location /api/v1/cart/ {
            proxy_pass http://cart-service;
        }

        # Order Service
        location /api/v1/orders/ {
            proxy_pass http://order-service;
        }

        # Payment Service
        location /api/v1/payments/ {
            proxy_pass http://payment-service;
        }
    }
}