# Generated by Django 5.0.14 on 2026-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=12337, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
