apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_DB: b3JkZXJfZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: ZWNvbW1lcmNl
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLUBrXmExNWdecHN0XmIrKWhnMm1rQD0kMzA2NSgkb0BvaXZ6dWNsN2Uyc2NAb282eHl3Cg==

  AUTH_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbEVybmVDd3l2NWdlc0IxRVh6M2wNCmFVa3UzNHV0amR1bTNaL1lXdm42M00waHVkYXN3NU1RN2kvZDJobW93YjZPdXQzbDBlalR3OVlySjBiSGlSbzANCjlSK0FuUnRxalZxNitGM3NmMTRBQ01ST3pTVTh3dEQ2dmNRcGxXME9vNW9sNnNMUlZmNm51L2ZOWjEwcmcwRnINClBQaHltQ1ppTzRKZ2tDTDlHdlJWMnM3UWxHemViK2JDelRjWmFRbk40ejk1SFZ3Z3pNSzVQM2UxS0lDdGdBcjYNCmVUc1pJV2lpMW0wam1jbzl6Umh1WHNkeVdDMytxKzVPaTNlRkl2QWVWbGlOZVQ2WTJ2MUUrTjJYRGJlU3MrS0ENCkVpTEY0ZDhJV2tGVFloRWF2VFJoY3NYcXgxMkQ4b0I0R0UzV044WDk2cExQTG5wY2lnM2tyUU9nU29pUTdabVUNCkd3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==
  ALLOWED_HOSTS: Kg==
  JWT_ALGORITHM: UlMyNTY=
  INTERNAL_SERVICE_SECRET: bXptZXYpZGljdCsrQGR2emttKXZfJTMteGdeeWhfYXUpOHFsPW9hYTQpemxwdCpedio=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  RABBITMQ_USER: Z3Vlc3Q=