apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
        - name: order-worker
          image: edddddr/order-service:latest
          command: ["python", "manage.py", "run_consumers"]

          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret